name: Build Suibase Daemon

on:
  push:
    paths:
      - "sui-binaries/triggers/suibase-daemon/Cargo.toml"
      - ".github/workflows/build-suibase-daemon.yml"
  workflow_dispatch:

env:
  asset_name: "suibase-daemon"

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from Cargo.toml
        id: cargo_version
        run: |
          cargo_filepath="triggers/${{ env.asset_name }}/Cargo.toml"
          if [ ! -f $cargo_filepath ]; then
            echo "$cargo_filepath does not exist"
            exit 1
          fi
          cargo_version=$(grep '^version' $cargo_filepath | sed 's/version = "\(.*\)"/\1/')
          echo "cargo_version=$cargo_version" >> $GITHUB_ENV
          echo "cargo_version: $cargo_version"
          tag_name="${{ env.asset_name }}-v$cargo_version"
          echo "tag_name=$tag_name" >> $GITHUB_ENV
          echo "tag_name: $tag_name"

      - name: Ensure Release exists and get upload URL
        id: release_vars
        uses: actions/github-script@v7
        with:
          script: |
            let tag_name = ${{ env.tag_name }};
            let upload_url;

            // Check if the release already exists
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const release = releases.find(release => release.tag_name === tag_name);

            if (release) {
              console.log(`Release already exists for ${tag_name}.`);
              upload_url = release.upload_url;
            } else {
              // Create the release if it does not exist
              const response = await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: tag_name,
                name: tag_name,
                draft: true,
                prerelease: false,
              });
              if (response.status >= 200 && response.status < 300 && response.data.upload_url) {
                console.log(`Release created for ${tag_name}.`);
                upload_url = response.data.upload_url;
              } else {
                throw new Error(`Failed to create release for ${tag_name}. Status: ${response.status}`);
              }
            }
            core.setOutput("upload_url", upload_url);

    outputs:
      cargo_version: ${{ env.cargo_version }}
      tag_name: ${{ env.tag_name }}
      upload_url: ${{ steps.release_vars.outputs.upload_url }}

  build-assets:
    needs: prepare-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
        include:
          - os: ubuntu-latest
            asset-name-suffix: ubuntu-x86_64
          - os: macos-latest
            asset-name-suffix: macos-arm64
          - os: macos-13
            asset-name-suffix: macos-x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Init asset_vars
        id: asset_vars
        uses: actions/github-script@v7
        with:
          script: |
            const tag_name = "${{ env.tag_name }}";
            console.log(`subsequent job tag_name: ${tag_name}`);
            const asset_name = `${tag_name}-${{ matrix.asset-name-suffix }}.tgz`;
            core.setOutput("asset_name", asset_name);

            let release;
            try {
               release = await github.rest.repos.getReleaseByTag({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 tag: tag_name,
               });
            } catch (error) {
               console.log(`getReleaseByTag info: ${error}`);
               release = { data: { assets: [] } }; // Assume no release found
            }
            const assetExists = release.data.assets.some(asset => asset.name === asset_name);
            if (assetExists) {
               console.log(`Asset exists for ${asset_name}`);
               core.setOutput("exists", "true");
            } else {
               console.log(`Asset does NOT exist for ${asset_name}`);
               core.setOutput("exists", "false");
            }

      - name: Build Asset
        if: steps.asset_vars.outputs.exists == 'true'
        run: |
          # For now, just simulate the build and validation of the artifact.
          asset_name="${{ steps.asset_vars.outputs.asset_name }}"
          echo "placeholder for build artifact" > $asset_name
          echo "Asset built: $asset_name"

      - name: Upload Asset to Release
        if: steps.asset_vars.outputs.exists == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const tag_name = "${{ env.tag_name }}";
            const asset_name = `${{ steps.asset_vars.outputs.asset_name }}`;
            const upload_url = '${{ needs.prepare-release.outputs.upload_url }}';

            const assetPath = './$asset_name';
            const contentType = 'application/gzip';
            const contentLength = fs.statSync(assetPath).size;

            const headers = {
              'content-type': contentType,
              'content-length': contentLength,
            };

            const uploadAssetResponse = await github.rest.repos.uploadReleaseAsset({
              url: upload_url,
              headers,
              name: asset_name,
              data: fs.readFileSync(assetPath),
            });

            if (uploadAssetResponse.status !== 201) {
              throw new Error(`Failed to upload ${asset_name}: ${uploadAssetResponse.status}`);
            }

            console.log(`Uploaded ${asset_name} successfully.`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify-and-publish-release:
    needs: build-assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Change Draft to Release when all assets present
        uses: actions/github-script@v7
        with:
          script: |
            const tag_name = "${{ env.tag_name }}";
            const expectedAssets = [
              `${tag_name}-ubuntu-x86_64.tgz`,
              `${tag_name}-macos-x86_64.tgz`,
              `${tag_name}-macos-arm64.tgz`
            ];
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const release = releases.find(release => release.tag_name === tag_name);
            if (!release) {
              throw new Error(`Release ${tag_name} not found`);
            }
            const asset_names = release.assets.map(asset => asset.name);
            const allAssetsPresent = expectedAssets.every(expectedAsset => asset_names.includes(expectedAsset));

            if (allAssetsPresent) {
              // Update the release to non-draft
              await github.rest.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id,
                draft: false,
              });
              console.log(`Release ${tag_name} published successfully.`);
            } else {
              throw new Error(`Not all expected assets are present for ${tag_name}.`);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
