name: Build Suibase Daemon

on:
  push:
    paths:
      - "sui-binaries/triggers/suibase-daemon/Cargo.toml"
      - ".github/workflows/build-suibase-daemon.yml"
  workflow_dispatch:

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Version from Cargo.toml
        id: cargo_version
        run: |
          suibase_cargo_version=$(grep '^version' triggers/suibase-daemon/Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "suibase_cargo_version=$VERSION" >> $GITHUB_ENV

      - name: Check if Release Exists
        id: check_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const version = "${{ env.suibase_cargo_version }}";
            const releaseExists = releases.some(release => release.tag_name === `suibase-daemon-v${version}`);
            console.log(`Release exists: ${releaseExists}`);
            return releaseExists;
          result-encoding: string

      - name: Create Release if Not Exists
        if: steps.check_release.outputs.result != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: suibase-daemon-v${{ env.suibase_cargo_version }}
          name: suibase-daemon-v${{ env.suibase_cargo_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
